#%RAML 1.0
title: demo-onprem
version: 1.0.0
description: api to test onprem monitoring

/onprem:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
      400:
        body:
          application/json:
            